KANOPI.md
This PR adds an additional readme style document to the base repository to help add additional documentation to the project to help onboard new developers, pass off to support at the end of the build, and write case studies after the project launches.
This doc defines the development of the project, not just the code as a traditional readme file does.
If merged, this PR would close #9
=> Adds KANOPI.md project description file

web/sites/default/settings.php
goes in the contrib folder.   example code from pantheon does not have that
=> fix path to the redis module

.circleci/config.yml, README.md
https://kanopi.teamwork.com/#/tasks/26934008
I have started the [explo repo](https://github.com/kanopi/explo) and [pantheon project](https://dashboard.pantheon.io/sites/5fc62ae6-4b5f-4c46-b994-dd8e5364212f#dev/code) using this starter.
Things seem to be working well (I can't be 100% due to current pantheon issues, but it's looking good so far).
This PR updates the README.md with some additional setup steps. 
It also removes the circleci environmental variable instructions from circleci's config.yml as we no longer need those (thanks for that!).
I'm keeping this in draft until I can fully validate things as I may need to make a few more changes.
=> Updates readme with github, pantheon and circleci setup steps

.docksal/etc/conf/settings.php
Also does some minor PHPCS updates. This file is automatically copied to ./web/sites/default/settings.local.php during the fin init process.
As a developer, any fork of this should be able to use the trusted host settings.
1. Create new fork
2. Fin init
3. Created site does not fail with the error "The provided host name is not valid for this server."
=> Update trusted host patterns to any

.docksal/etc/conf/settings.php
Since this file becomes /sites/settings.local.php, the added lines will override the minifyhtml config so it can stay enabled and configured.
=> over-ride minifyhtml configuration locally

.docksal/etc/conf/settings.php
Webp images don't work when working locally.
Adding settings.local.php `$config['image.settings']['allow_insecure_derivatives'] = TRUE;` to settings fixes this issue.
Related issue https://www.drupal.org/project/imageapi_optimize_webp/issues/3246333
1. Upload an image to a field that is using the webp generated image style.
2. Save
3. The webp should now be displayed on the frontend locally.
=> Set allow_insecure_derivatives to true for webp images 

.circleci/config.yml
Skips deploy to pantheon on CI for dependabot branches.
=> Skipping dependabot deploys

.circleci/scripts/pantheon/dev-multidev
Updates the multidev script to include the --clone-content flag.
Reference: https://github.com/pantheon-systems/terminus-build-tools-plugin#buildenvcreate
=> Adds --clone-content flag to build:env:create

pantheon.yml
The following will force HTTPS on Pantheon and for HSTS. More information can be found here https://pantheon.io/docs/pantheon-yml#enforce-https--hsts
=> Added HSTS for Pantheon

.circleci/config.yml, .docksal/etc/nginx/vhost-overrides.conf, README.md
Updates to make starter work with Drupal 10.1
- Updates the image to php 8.1 in .circleci/config.yml
- Updates README to reflect slightly different steps/options for site spin-up
- Commented out the image proxy code in the vhosts override file in .docksal. This is a band-aid fix. We need to eventually figure out how to get the proxy to work with Drupal 10.1.
* https://github.com/kanopi/drupal-starter/issues/115
=> 115 - D10 adjustments

.docksal/etc/conf/settings.php
On local environments, skipping file permissions hardening prevents the sites/default/ folder from having edit permissions revoked for the docksal user. This especially comes up when upgrading Drupal, when scaffold wants to delete files in sites/default/.
=> Skip file permissions hardening on local.

composer.json
The patch for search_api_autocomplete no longer applies and can be remove. Fix was merged into stable release.
https://www.drupal.org/project/search_api_autocomplete/issues/3382226
composer install
https://github.com/kanopi/drupal-starter/issues/129
=> issue-129 - removes patch for search_api_autocomplete

composer.json, rector.php
> As a developer, I need to keep Rector updated to track Drupal 11 deprecations.
=> Upgrades Drupal Rector for Drupal 11

.docksal/commands/init-site
[Issue 138](https://github.com/kanopi/drupal-starter/issues/138)
> As a developer, I need to prevent blackfire errors when running fin init.
1. Pull this branch
2. Run fin init
3. Validate no errors
[Slack thread](https://kanopi.slack.com/archives/C04CRR2UA/p1702335730704959)
=> issue 138 - fixes blackfire error

.docksal/commands/init
Closes #148 
Fix courtesy of @sean-e-dietrich in Slack.
=> Replaces Drush Launcher. Tells Docksal where to find Drush.

.github/config/branch-protection/main.json, .github/config/repo.json, .github/config/topics.json, docs/INSTALLATION.md
Continues to add CLI instructions to the Installation doc.  This should greatly reduce the time it takes to spin up a site.
Need to step through the instructions, validate they work, and see if we need any more/less.
We can also go into the new `.github/config/` files and configure things further to our liking.
1. Follow the steps in /docs/INSTALLATION.md and confirm they work.
This would close #150
=> Adds GitHub CLI documentation

.docksal/commands/install-theme-tools
npm ci performs a clean install of all existing dependencies, whereas npm install attempts to update current dependencies when possible.
=> Use npm ci and not npm install

.docksal/commands/refresh
`fin rebuild` exists that includes `composer install`.  Build needs a refresh command that doesn't have it.
The more important aspect is to gate the db request only if the `config/core.extention.yml` exists.
=> Removes composer install, adds fencing for first time run

composer.json
Updates for Drupal 10.3
Will also close PRs #189 and #185 
* Updates Drupal
* Updates rector
* Upgrading composer/installer to 2.3 allows us to remove all the standard installer-types.
* Removes merged patches
* Updates the recipe unpack repo to Github from shakier Gitlab
Tag a new 10.3 release after this is merged.
=> Updates for Drupal 10.3

.circleci/config.yml
Added condition to not run post build steps on the main branch.
This will stop the trigger from happening when there are no tests on the main branch.
=> Conditional Build Steps

.circleci/config.yml
CircleCI API triggers can cancel other running workflows, which is unexpected and can cause issues.
https://discuss.circleci.com/t/prevent-workflow-cancellation-when-triggering-pipeline-via-rest-api/40120
This PR removes the trigger code and reverts to the CircleCI `requires` way of linking jobs. You can now see the dependency tree of jobs in the graph properly.
The CircleCI integration in GitHub now allows for deep linking to the separate jobs in a workflow from the PR, so the requirement of running the trigger to get a link to jobs within a workflow is no longer necessary.
=> Remove the Trigger orb

.docksal/commands/init
This make `fin init` do nothing in the latest release of Docksal.
Thanks to @shirazd for finding it.
=> Removes looking for fin. This breaks in the latest release of Docksal

tests/cypress/reporter-config.json
Sick of having to open every mochareport-001, 002, 003 named files to find the test you want? 
This updates the names of the report to be [pass/fail]--[report_name]--[datetime].html. It also turns off JSON to get rid of some files (I don't think we use the report data as JSON), and adds charts.
1. Update a local with this file change 
2. run `fin cypress run --spec cypress/e2e/system-checks.cy.js`
3. view the report in `cypress/results`
=> Add test name and pass/fail to Cypress reports

composer.json
https://www.drupal.org/project/drupal/issues/3478895#comment-15816720
> catch at Third and Grove commented 16 October 2024 at 02:39
> It's fine to set it to allowed false because it only runs during tests. Not sure where would be best to document this. I guess a change record would be a start.
> We might want to file an upstream issue asking whether it really needs to be a dependency too though, or at least find the upstream commit where it was added.
=> Disallow tbachert/spi composer plugin

.docksal/etc/conf/development.services.yml
Add cache tags debug to `development.services.yml`
More information can be found here https://www.drupal.org/docs/develop/development-tools/disabling-and-debugging-caching#s-enable-render-cache-debugging
Comment out http.response.debug_cacheability_headers: true due to many 500 errors.
Uncomment renderer.config object in `development.services.yml`
n/a
=> Add cache tags debug to development.services. Comment out cacheability_headers due to 500 errors.

.docksal/commands/init, .docksal/commands/testenv, README.md
To spin up an environment with a locally created database, you can use the new `testenv` command.
Run `fin testenv anynameyourwant` and it will create a Drupal site for you at anynameyourwant.docksal.site using the minimal profile.
You can also provide a second argument to specify a different profile or recipe.
Using Standard profile:
`fin testenv mynewsite standard`
Using a recipe.
`fin testenv mynewsite recipes/saplings`
Closes #177
=> Adds a `testenv` command to spin up a testing environment

.circleci/config.yml
Added ability for Cron Job to be added and scheduled through CircleCI UI triggers.
This will also allow the end user to quickly reference the environment they would like to use without having to push multiple workflows.
=> Pantheon Cron Job

pantheon.yml
Closes #230
Is this needed? If so, we need to add it. If not, we need to remove it from the pantheon.yml
```
sync_code:
after:
- type: webphp
description: Push changes back to GitHub if needed
script: private/scripts/quicksilver/quicksilver-pushback/push-back.php
```
@sean-e-dietrich:  I don't think we need it honestly. I thought it was buggy but I also know it hasn't been used all the time.
=> Removes unused script

docs/ABOUT.md
Updates recipes composer installers path.
=> Updates recipes path

.circleci/config.yml
Updated CircleCI to use workflows instead of using stricter items like trigger names and using more workflow parameters.
The process with this is that it makes it less strict in the way names are used when creating triggers and more flexible to use in the Trigger Pipeline.
=> Updated CircleCI to use workflows

composer.json
Teamwork Ticket(s): https://kanopi.teamwork.com/app/tasks/29714324
This PR adds [mglaman/phpstan-drupal](https://github.com/mglaman/phpstan-drupal) as requested in [issue-257](https://github.com/kanopi/drupal-starter/issues/257) and resolves some of the phpstan errors reported in [arbor issue-26](https://github.com/kanopi/arbor/issues/26)
1. These changes eliminated the "extends unknown class" [PHPstan errors](https://app.circleci.com/pipelines/github/kanopi/ucsf-deb/12/workflows/2f359fb9-fcc5-4e56-b03b-2a3fd5a84de1/jobs/113) on the ucsf-deb project. [Here](https://app.circleci.com/pipelines/github/kanopi/ucsf-deb/15/workflows/6a3505e4-a0f1-4d91-8cf6-1f1271945de1) is the successful phpstan test after I made these changes.
=> issue-257 - adds phpstan-drupal dependency
