kanopi/drupal-starter

KANOPI.md
Updates a Team and Links sections of the Kanopi Read me file.
N/A
N/A
N/A
N/A
N/A
=> Updates KANOPI.md

README.md
We have all these readme's for projects that are often acronyms and it's a pain to not just have a direct link to the real website so you know what you're building
=> Update the readme to have a link to the actual website

.docksal/docksal.env
> As a developer, I need to start with the latest CLI
=> Update to the latest CLI

KANOPI.md
> As an agency that works on Drupal sites, we should document information that could be used in a case study on Drupal.org
N/A
N/A
N/A
N/A
N/A
=> Add case study style questions to the Development notes section

build-providers.json, pantheon.yml, web/private/scripts/drush_config_import/drush_config_import.php
> As a developer, I quicksilver scripts to run on the Pantheon development environment
Sean and I chatted about how best to manage drush environment update commands.  These are a couple of tweaks before any other changes happen
=> Pantheon quicksilver deploy tweaks

composer.json
> As a developer, I need to start with the Key module installed.
=> Adds the Key module

README.md, composer.json, lefthook.yml
> As a developer, I need to start with a story.
_A few sentences describing the overall goals of the pull request's commits.
What is the current behavior of the app? What is the updated/expected behavior
with this PR? **Include your acceptance critiera!** If your tasks were well-written, you can probably copy/paste some of this._
[link_to_relevant_multidev_or_test_site](insert_link_here)
* [insert_ticket_name_here](insert_link_here)
1. A list of steps to validate
1. Include direct links to test sites -- specific nodes, admin screens, etc
1. Be explicit
_Notes regarding deployment of the contained body of work. These should note any
new dependencies, new scripts, etc._
=> Updates composer scripts and documentation

.circleci/config.yml
> As a developer, I need to start with a story.
_A few sentences describing the overall goals of the pull request's commits.
What is the current behavior of the app? What is the updated/expected behavior
with this PR? **Include your acceptance critiera!** If your tasks were well-written, you can probably copy/paste some of this._
[link_to_relevant_multidev_or_test_site](insert_link_here)
* [insert_ticket_name_here](insert_link_here)
1. A list of steps to validate
1. Include direct links to test sites -- specific nodes, admin screens, etc
1. Be explicit
_Notes regarding deployment of the contained body of work. These should note any
new dependencies, new scripts, etc._
=> Updates image to 7.x-php7.4

composer.json
> As a developer, I need to to use Launch Checklist from Drupal.org
=> Require Launch Checklist from drupal.org

.docksal/commands/pa11y, .docksal/docksal.yml
=> add missing pally docksal stuff

composer.json
added allow-plugin for composer security
=> Added Allow Plugins

composer.json
> As a developer, I need to start with a story.
_A few sentences describing the overall goals of the pull request's commits.
What is the current behavior of the app? What is the updated/expected behavior
with this PR? **Include your acceptance critiera!** If your tasks were well-written, you can probably copy/paste some of this._
[link_to_relevant_multidev_or_test_site](insert_link_here)
* [insert_ticket_name_here](insert_link_here)
1. A list of steps to validate
1. Include direct links to test sites -- specific nodes, admin screens, etc
1. Be explicit
_Notes regarding deployment of the contained body of work. These should note any
new dependencies, new scripts, etc._
=> Adds the Security Kit module

composer.json
=> Adds Fancy File Delete

.circleci/config.yml, .docksal/commands/init-site, .docksal/commands/rename-kdcl-basic, README.md, composer.json, lefthook.yml
clean up a couple of things after setting up a site
=> Kdcl tweaks

README.md
Changed ReadMe.md to adhere to coding standards of 80 characters
https://kanopi.teamwork.com/#/tasks/28860684
=> coding standards readme.md

phpstan.neon
Allows for drupal/coder and phpstan to co-exist peacefully.
=> Updates phpstan from max to 5.

.docksal/commands/open
Should close #102 
Updated to make it https: from Kate and David's scripts
=> Creates the open Docksal command

docs/INSTALLATION.md
=> Adds CLI Installation Method

.docksal/commands/config-capture, README.md
=> Adds `config-capture` command

composer.json
https://www.drupal.org/project/ui_patterns_settings/issues/3409221
=> Patches ui_patterns_settings

.docksal/docksal.env
=> Update docksal.env to docksal/cli:php8.2

.circleci/config.yml, .docksal/commands/recipe-apply, .docksal/commands/recipe-configure, .docksal/docksal.env, README.md, composer.json, docs/DEFAULT_CONTENT.md, pantheon.yml
Adds Default Content module to --dev and documents it
Closes #186 
Upgrades PHP to 8.3
Closes #179 
Moves recipe folder above webroot
Closes #193
=> More improvements for 10.3

.docksal/etc/conf/settings.php
This adds a random id for the hash_salt to the file that is symlinked to settings.local.php
=> Adds hash_salt to local settings

.circleci/config.yml, .twig-cs-fixer.php, README.md, composer.json
The following solution is being adopted by Drupal core.  [RTBC issue](https://www.drupal.org/project/drupal/issues/3284817).
Closes #203 
Run the following commands
=> Adds Twig Coding Standards Fixer

pantheon.yml
https://docs.pantheon.io/guides/new-relic/monitor-new-relic\#enable-drupal-hooks--modules-metrics
=> update pantheon.yml to make sure new relic tracks drupal

composer.json
Closes #214 
Adds and ran
https://github.com/ergebnis/composer-normalize
=> Normalizes composer.json

composer.json
Redis was moved to kanopi/saplings-pantheon
=> Removes Redis

.docksal/commands/cypress, .docksal/commands/open
=> Updates cypress command to accept url input

composer.json
=> Updates Drupal to 11.1

composer.json
It accidentally got added back.
Teamwork Ticket(s): [insert_ticket_name_here](insert_link_here)
> As a developer, I need to start with a story.
_A few sentences describing the overall goals of the pull request's commits.
What is the current behavior of the app? What is the updated/expected behavior
with this PR?_
* A list describing how the feature should behave
* e.g. Clicking outside a modal will close it
* e.g. Clicking on a new accordion tab will not close open tabs
* A list of things the code reviewer or project manager should know
* e.g. There is a known Javascript error in the console.log
* e.g. On any `multidev`, the popup plugin breaks.
1. A list of steps to validate
1. Include direct links to test sites (specific nodes, admin screens, etc)
1. Be explicit …
=> Remove Redis again.

composer.json
Thanks to @banoodle for finding this.
=> Update Pantheon integration package

.circleci/config.yml, docs/INSTALLATION.md
- Documents the CircleCI cron workflow.
- Fixes issues with workflow naming in circleci config.
=> Document cron

composer.json
Updates paths to lint from "docroot/..." to "web/..."
=> Fixes Twig lint directory paths to be scanned.

composer.json
> As a developer, I need to update Drupal and Rector to the latest versions.
=> Dependency updates

CLAUDE.md
The file maintains its existing high-quality structure covering all the essential aspects:
- Project overview with key technologies (Drupal 11, Saplings, DDEV/Docksal)
- Comprehensive command references for both development environments
- Detailed architecture information including theme system, content architecture, and custom code structure
- Important patterns for Recipe system and component development
- Deployment and Pantheon-specific configuration details
This CLAUDE.md will effectively guide future Claude Code instances in understanding and working with this modern Drupal 11 starter project.
=> Add a readme for Claude Code
